# Generated by Django 4.0 on 2022-02-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image_1_alter_post_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='images/blog/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='images/blog/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_6',
            field=models.ImageField(blank=True, upload_to='images/blog/'),
        ),
        migrations.AddField(
            model_name='post',
            name='main_image_index',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
