# Generated by Django 4.0 on 2022-02-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image_4_post_image_5_post_image_6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image_index',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1),
        ),
    ]
