# Generated by Django 3.2.5 on 2022-04-08 22:25

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_organization_google_maps_url'),
        ('blog', '0006_alter_post_main_image_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.organization'),
        ),
        migrations.AddField(
            model_name='reference',
            name='category',
            field=models.CharField(choices=[('page', 'page'), ('scientific article', 'scientific article'), ('video', 'video'), ('wikipedia', 'wikipedia')], default='page', max_length=100),
        ),
        migrations.AddField(
            model_name='tag',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(blank=True, upload_to=blog.models.uploadPath('blog/images/', '1')),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, upload_to=blog.models.uploadPath('blog/images/', '2')),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_3',
            field=models.ImageField(blank=True, upload_to=blog.models.uploadPath('blog/images/', '3')),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_4',
            field=models.ImageField(blank=True, upload_to=blog.models.uploadPath('blog/images/', '4')),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_5',
            field=models.ImageField(blank=True, upload_to=blog.models.uploadPath('blog/images/', '5')),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_6',
            field=models.ImageField(blank=True, upload_to=blog.models.uploadPath('blog/images/', '6')),
        ),
    ]
