# Generated by Django 4.0 on 2022-04-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publication_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='publication_date',
        ),
    ]
