# Generated by Django 4.2.30 on 2026-09-30 15:38

from datetime import datetime, time, timedelta

from django.db import migrations, models
from django.utils import timezone


def migrate_task_data(apps, schema_editor):
    database = schema_editor.connection.alias
    Task = apps.get_model('tasks', 'Task')
    Category = apps.get_model('tasks', 'Category')
    Preferences = apps.get_model('tasks', 'TasksPreference')
    preferences, _ = Preferences.objects.using(database).get_or_create(pk=1)
    default_lead = timedelta(minutes=preferences.default_reminder_minutes)

    for task in Task.objects.using(database).all().iterator():
        if task.category:
            category, _ = Category.objects.using(database).get_or_create(name=task.category.strip())
            task.categories.add(category)

        task.priority = {'low': 1, 'medium': 3, 'high': 5}.get(task.priority, 3)
        if task.due_date:
            due_at = datetime.combine(task.due_date, time(9))
            task.due_at = timezone.make_aware(due_at, timezone.get_current_timezone())
        if task.reminder_at:
            task.reminder_enabled = True
            if not task.due_at:
                task.due_at = task.reminder_at + default_lead
        task.save(using=database, update_fields=['priority', 'due_at', 'reminder_enabled'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TasksPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_reminder_minutes', models.PositiveIntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (60, '1 hour'), (120, '2 hours'), (360, '6 hours'), (720, '12 hours'), (1440, '1 day'), (2880, '2 days'), (10080, '1 week')], default=60)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.category'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_task_data, migrations.RunPython.noop, hints={'model_name': 'task'}),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminder_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
