# Generated by Django 4.2.30 on 2026-09-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_taskspreference_remove_task_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#f2d6c2', 'Peach'), ('#f3dfb4', 'Gold'), ('#eee8b6', 'Butter'), ('#e4e8b8', 'Olive'), ('#d6e4b9', 'Moss'), ('#c5dfc5', 'Sage'), ('#bfe0d4', 'Mint'), ('#b9dedc', 'Teal'), ('#c0dfeb', 'Sky'), ('#c7d9eb', 'Blue'), ('#ccd0e8', 'Periwinkle'), ('#d7cae5', 'Lavender'), ('#e3c8e1', 'Lilac'), ('#edc9d4', 'Rose'), ('#e9c4bd', 'Terracotta'), ('#ded0bc', 'Stone'), ('#cad7cc', 'Eucalyptus'), ('#c6d6d9', 'Slate'), ('#e4d3a3', 'Mustard'), ('#dbd8bf', 'Khaki')], default='#c5dfc5', max_length=7),
        ),
    ]
