# Generated by Django 4.0 on 2022-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('notification_email', models.EmailField(max_length=254)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('country_phone_code', models.PositiveSmallIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=20)),
                ('personal_statement', models.TextField(blank=True)),
                ('personal_website', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('snapchat_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=200)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_short_name', models.CharField(blank=True, max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('minor', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('thesis_title', models.CharField(blank=True, max_length=200)),
                ('gpa', models.DecimalField(decimal_places=1, max_digits=3)),
                ('gpa_total', models.DecimalField(decimal_places=1, max_digits=3)),
                ('school_description', models.TextField(blank=True)),
            ],
        ),
    ]
