# Generated by Django 4.0 on 2022-01-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinformation',
            old_name='personal_website',
            new_name='website_url',
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='website_statement',
            field=models.TextField(blank=True),
        ),
    ]
