# Generated by Django 4.0 on 2022-01-17 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_personal_website_basicinformation_website_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('degree_type', models.CharField(choices=[('Doctoral', 'Doctoral'), ("Master's", "Master's"), ("Bachelor's", "Bachelor's"), ('Other', 'Other')], max_length=200)),
                ('start_data', models.DateField()),
                ('end_date', models.DateField()),
                ('positions', models.CharField(max_length=200)),
                ('organizations', models.CharField(max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_short_name', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('supervisor', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HonorsAndAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree_type', models.CharField(choices=[('Doctoral', 'Doctoral'), ("Master's", "Master's"), ("Bachelor's", "Bachelor's"), ('Other', 'Other')], max_length=200)),
                ('start_data', models.DateField()),
                ('end_date', models.DateField()),
                ('positions', models.CharField(max_length=200)),
                ('organizations', models.CharField(max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senders_name', models.CharField(max_length=200)),
                ('senders_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presentations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('speaker_index', models.PositiveSmallIntegerField()),
                ('conference', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('citations', models.CharField(blank=True, max_length=10)),
                ('extra_info', models.CharField(blank=True, max_length=200)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('pi', models.CharField(max_length=500)),
                ('agency', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('awarded', 'awarded'), ('pending', 'pending')], max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('extra_info', models.CharField(blank=True, max_length=200)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=200)),
                ('issue_etc', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('citations', models.CharField(blank=True, max_length=10)),
                ('extra_info', models.CharField(blank=True, max_length=200)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('skill_description', models.CharField(blank=True, max_length=200)),
                ('uncategorized', models.BooleanField(default=True)),
                ('data_science', models.BooleanField(default=False)),
                ('machine_learning', models.BooleanField(default=False)),
                ('computer_languages', models.BooleanField(default=False)),
                ('software', models.BooleanField(default=False)),
                ('industry', models.BooleanField(default=False)),
                ('polymers', models.BooleanField(default=False)),
                ('chemistry', models.BooleanField(default=False)),
                ('techniques', models.BooleanField(default=False)),
                ('soft_skills', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organizations')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='school_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='thesis_title',
            new_name='thesis',
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='orcid_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='publons_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='researchgate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='scholar_url',
            field=models.URLField(blank=True),
        ),
    ]
