# Generated by Django 4.0 on 2022-01-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_organization_city_organization_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company_short_name',
        ),
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='honorandaward',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization'),
        ),
    ]
