# Generated by Django 4.0 on 2022-01-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_experience_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
