# Generated by Django 4.0 on 2022-01-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_presentation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='score',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
