# Generated by Django 4.0 on 2022-01-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_skill_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='chemistry',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='computer_languages',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='data_science',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='machine_learning',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='polymers',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='score',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='soft_skills',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='software',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='techniques',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='uncategorized',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(default='temp', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skill',
            name='skills',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
    ]
