# Generated by Django 4.0 on 2022-01-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_skill_chemistry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
