# Generated by Django 4.0 on 2022-01-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_leadership_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advising',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
