# Generated by Django 4.0 on 2022-01-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_mentoring_end_date_alter_teaching_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoring',
            name='program',
            field=models.CharField(choices=[('MSE Industry Mentoring', 'MSE Industry Mentoring'), ('Mentor Jackets', 'Mentor Jackets'), ('IITR AMP', 'IITR AMP'), ('Other', 'Other')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
