# Generated by Django 4.0 on 2022-01-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_mentoring_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorandaward',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
