# Generated by Django 4.0 on 2022-01-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_honorandaward_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='course_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
