# Generated by Django 4.0 on 2022-01-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_teaching_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaching',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='teaching',
            name='start_date',
        ),
        migrations.AddField(
            model_name='teaching',
            name='semester',
            field=models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=200),
        ),
        migrations.AddField(
            model_name='teaching',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020),
            preserve_default=False,
        ),
    ]
