# Generated by Django 3.2.5 on 2022-01-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_teaching_end_date_remove_teaching_start_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Skillset',
        ),
        migrations.RenameField(
            model_name='advising',
            old_name='start_data',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='mentoring',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
