# Generated by Django 3.2.5 on 2022-01-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20220121_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('under review / submitted', 'under review / submitted'), ('submitting soon', 'submitting soon'), ('published', 'published'), ('in progress', 'in progress')], default='in progress', max_length=200),
        ),
    ]
