# Generated by Django 3.2.5 on 2022-01-22 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_publication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='extra_info',
        ),
    ]
