# Generated by Django 3.2.5 on 2022-01-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_publication_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='group',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=200),
            preserve_default=False,
        ),
    ]
