# Generated by Django 4.0 on 2022-01-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_skillset_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('under review / submitted', 'under review / submitted'), ('submitting next', 'submitting next'), ('published', 'published'), ('in progress', 'in progress')], default='in progress', max_length=200),
        ),
    ]
