# Generated by Django 4.0 on 2022-02-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_workhighlights'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkHighlights',
            new_name='WorkHighlight',
        ),
    ]
