# Generated by Django 4.0 on 2022-02-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_workhighlights_workhighlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhighlight',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/work_highlights'),
        ),
    ]
