# Generated by Django 4.0 on 2022-02-07 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_workhighlight_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhighlight',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.organization'),
        ),
    ]
