# Generated by Django 4.0 on 2022-02-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_workhighlight_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='resume_tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
