# Generated by Django 4.0 on 2022-02-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_honorandaward_featured_honorandaward_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
