# Generated by Django 4.0 on 2022-03-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_advising_diversity_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advising',
            name='diversity_tags',
            field=models.CharField(blank=True, choices=[('women', 'women'), ('african-americans', 'african-americans'), ('internationals', 'internationals'), ('other minorities', 'other minorities'), ('first-generations', 'first-generations'), ('disabled', 'disabled'), ('none', 'none')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='diversity_tags',
            field=models.CharField(blank=True, choices=[('women', 'women'), ('african-americans', 'african-americans'), ('internationals', 'internationals'), ('other minorities', 'other minorities'), ('first-generations', 'first-generations'), ('disabled', 'disabled'), ('none', 'none')], default='none', max_length=200),
        ),
    ]
