# Generated by Django 4.0 on 2022-03-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_advising_diversity_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiversityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='advising',
            name='diversity_tags',
        ),
        migrations.RemoveField(
            model_name='mentoring',
            name='diversity_tags',
        ),
        migrations.AddField(
            model_name='advising',
            name='diversity_tags',
            field=models.ManyToManyField(blank=True, to='base.DiversityTag'),
        ),
        migrations.AddField(
            model_name='mentoring',
            name='diversity_tags',
            field=models.ManyToManyField(blank=True, to='base.DiversityTag'),
        ),
    ]
