# Generated by Django 4.0 on 2022-03-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='start_year',
            field=models.PositiveSmallIntegerField(default=2012),
            preserve_default=False,
        ),
    ]
