# Generated by Django 3.2.5 on 2022-03-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_reference_start_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
