# Generated by Django 3.2.5 on 2022-04-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='school_short_name',
        ),
        migrations.AddField(
            model_name='education',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.organization'),
            preserve_default=False,
        ),
    ]
