# Generated by Django 3.2.5 on 2022-04-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20220404_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
    ]
