# Generated by Django 4.0 on 2022-04-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_organization_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_in_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='email_out_log',
            field=models.TextField(blank=True),
        ),
    ]
