# Generated by Django 4.0 on 2022-04-12 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_message_email_in_log_message_email_out_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email_in_log',
            new_name='email_in_success',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='email_out_log',
            new_name='email_out_success',
        ),
    ]
