# Generated by Django 4.0 on 2022-04-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_message_email_in_success_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(max_length=100, null=True)),
                ('http_accept', models.CharField(max_length=100, null=True)),
                ('http_accept_language', models.CharField(max_length=50, null=True)),
                ('http_host', models.CharField(max_length=50, null=True)),
                ('http_referer', models.CharField(max_length=100, null=True)),
                ('http_user_agent', models.CharField(max_length=400, null=True)),
                ('remote_host', models.CharField(max_length=50, null=True)),
                ('remote_user', models.CharField(max_length=50, null=True)),
                ('remote_port', models.CharField(max_length=50, null=True)),
                ('request_method', models.CharField(max_length=50, null=True)),
                ('server_name', models.CharField(max_length=50, null=True)),
                ('server_port', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
