# Generated by Django 4.0 on 2022-04-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_remove_analytics_http_accept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='user_ip',
            new_name='remote_addr',
        ),
    ]
