# Generated by Django 4.0 on 2022-04-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_rename_user_ip_analytics_remote_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='visited_page',
            field=models.CharField(default='/', max_length=50),
        ),
    ]
