# Generated by Django 3.2.5 on 2022-04-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_analytics_visited_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analytics',
            new_name='Analytic',
        ),
    ]
