# Generated by Django 3.2.5 on 2022-04-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_rename_analytics_analytic'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='medium_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='towardsdatascience_url',
            field=models.URLField(blank=True),
        ),
    ]
