# Generated by Django 3.2.5 on 2022-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20220412_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hidden_field',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
