# Generated by Django 3.2.5 on 2022-12-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_message_hidden_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadership',
            name='short_title',
            field=models.CharField(default='abc', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
