# Generated by Django 3.2.5 on 2022-12-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20221205_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentation',
            old_name='extra_info',
            new_name='issue_etc',
        ),
    ]
