# Generated by Django 3.2.5 on 2022-12-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_rename_extra_info_presentation_issue_etc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('under review / submitted', 'under review / submitted'), ('submitting next', 'submitting next'), ('published', 'published'), ('in progress', 'in progress'), ('preprint', 'preprint')], default='in progress', max_length=200),
        ),
    ]
