# Generated by Django 3.2.5 on 2022-12-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_review_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='website_tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
