# Generated by Django 3.2.5 on 2023-02-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_basicinformation_website_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.PositiveSmallIntegerField(default=50)),
                ('group', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=100)),
                ('score', models.PositiveSmallIntegerField(default=50)),
                ('start_year', models.PositiveSmallIntegerField(default=2006)),
                ('category', models.ManyToManyField(to='base.SkillCategory')),
            ],
        ),
    ]
