# Generated by Django 3.2.5 on 2023-02-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_alter_skill_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='cv_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='resume_statement',
            field=models.TextField(blank=True),
        ),
    ]
