# Generated by Django 3.2.5 on 2023-02-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_auto_20230209_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
