# Generated by Django 4.0.3 on 2023-05-31 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_alter_jobdescription_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobDescription',
        ),
    ]
