# Generated by Django 4.2.30 on 2026-09-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_publication_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
