# Generated by Django 4.2.30 on 2026-09-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_presentation_updated_at_publication_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='updated_at',
        ),
    ]
