# Generated by Django 4.2.30 on 2026-09-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_remove_presentation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
