# Generated by Django 4.2.30 on 2026-09-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_publication_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='authors_full',
            field=models.TextField(blank=True),
        ),
    ]
